import { getStore } from '@netlify/blobs';
import crypto from 'node:crypto';

const store=getStore('sdps-sports-data');
const files=getStore('sdps-sports-files');
const HOUSES=['Aryabhatta House','Ashoka House','Gautam House','Chanakya House'];
const GAMES=['Athletics','Football','Cricket','Basketball','Volleyball','Badminton','Table Tennis','Tennis','Kho-Kho','Kabaddi','Chess','Carrom','Handball','Hockey','Throwball','Long Jump','High Jump','Shot Put','Discus Throw','Javelin Throw','100m','200m','400m','800m','1500m','Relay','Yoga','Skipping'];
const CATS=['Group A','Group B','Group C','Group D'];
const full=new Set(['owner','sports_teacher']);
const staff=new Set(['owner','sports_teacher','house_teacher','prefect']);
const uid=()=>crypto.randomUUID();
const hash=p=>new Promise((res,rej)=>{const salt=crypto.randomBytes(16);crypto.scrypt(p,salt,64,(e,d)=>e?rej(e):res(`${salt.toString('hex')}:${d.toString('hex')}`))});
const verify=(p,h)=>new Promise(r=>{try{const [saltHex,digestHex]=String(h).split(':');if(!saltHex||!digestHex)return r(false);crypto.scrypt(p,Buffer.from(saltHex,'hex'),64,(e,d)=>r(!e&&crypto.timingSafeEqual(d,Buffer.from(digestHex,'hex'))))}catch{r(false)}});
async function get(k,def=[]){return (await store.get(k,{type:'json'}))??def}
async function set(k,v){await store.setJSON(k,v)}
async function init(){if(await store.get('initialized'))return;const hp=await hash('ChangeMe123!'),sp=await hash('sdpsept');await set('users',[{id:uid(),user_id:'owner',password_hash:hp,name:'School Owner',role:'owner',active:true},{id:uid(),user_id:'SDPSEPT',password_hash:sp,name:'Sports Teacher',role:'sports_teacher',active:true}]);await set('settings',{school_name:'S.D.Public School Kumhrar Patna-07',address:'Kumhrar, Patna-07',principal_name:'',sports_teacher_name:'',houses:HOUSES});for(const k of ['students','events','results','participation','assessments','annual','certificates','gallery','reset_requests','audit','teacher_profiles','prefect_profiles'])await set(k,[]);await set('initialized',true)}
const secret=()=>process.env.SDPS_SESSION_SECRET||'change-this-netlify-secret';
const sign=s=>crypto.createHmac('sha256',secret()).update(s).digest('base64url');
function cookie(u){const p=Buffer.from(JSON.stringify(u)).toString('base64url');return `sdps_session=${p}.${sign(p)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`}
function session(req){const c=req.headers.get('cookie')||'',m=c.match(/(?:^|; )sdps_session=([^;]+)/);if(!m)return null;const [p,s]=m[1].split('.');if(!p||!s||sign(p)!==s)return null;try{return JSON.parse(Buffer.from(p,'base64url').toString())}catch{return null}}
const json=(body,status=200,headers={})=>({statusCode:status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers},body:JSON.stringify(body)});
const parse=async req=>{try{return await req.json()}catch{return {}}};
function allowed(me,item){return full.has(me.role)||me.role==='prefect'||(me.role==='house_teacher'&&item.house===me.house)}
async function audit(me,action,detail){const a=await get('audit',[]);a.unshift({id:uid(),at:new Date().toISOString(),user_id:me.user_id,role:me.role,action,detail});await set('audit',a.slice(0,1000))}
export default async req=>{try{await init();const u=new URL(req.url),path=u.pathname.replace(/^\/api/,'')||'/';let me=session(req);
 if(path==='/login'&&req.method==='POST'){const b=await parse(req),users=await get('users',[]),x=users.find(x=>x.user_id===b.user_id&&x.active);if(!x||!(await verify(b.password||'',x.password_hash)))return json({error:'Invalid User ID or password'},401);const h={};h['Set-Cookie']=cookie({id:x.id,user_id:x.user_id,name:x.name,role:x.role,house:x.house||null});await audit(x,'login','Successful login');return json({ok:true,user:{user_id:x.user_id,name:x.name,role:x.role,house:x.house||null}},200,h)}
 if(path==='/logout'){return json({ok:true},200,{'Set-Cookie':'sdps_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict'})}
 if(path.startsWith('/file/')&&req.method==='GET'){const key=decodeURIComponent(path.slice(6));const obj=await files.get(key,{type:'arrayBuffer'});if(!obj)return {statusCode:404,body:'Not found'};return {statusCode:200,headers:{'Content-Type':'image/*','Cache-Control':'public,max-age=31536000,immutable'},body:Buffer.from(obj).toString('base64'),isBase64Encoded:true}}
 if(!me)return json({error:'Login required'},401);
 if(path==='/me')return json({user:me});
 if(path==='/data'&&req.method==='GET'){const names=['settings','students','events','results','participation','assessments','annual','certificates','gallery','teacher_profiles','prefect_profiles','users'];const o={};for(const n of names)o[n]=await get(n,[]);o.students=o.students.filter(s=>allowed(me,s)||me.role==='student'&&s.admission_no===me.user_id);if(me.role==='house_teacher'){for(const n of ['results','participation','assessments','annual','certificates'])o[n]=o[n].filter(x=>allowed(me,x)||!x.house)}if(me.role==='student'){for(const n of ['participation','assessments','annual','certificates'])o[n]=o[n].filter(x=>x.student_id===me.user_id||x.admission_no===me.user_id);o.events=[];o.gallery=[];o.results=[];o.users=[]}if(!full.has(me.role)){o.users=[];o.teacher_profiles=[];o.prefect_profiles=[]}return json(o)}
 if(path==='/password'&&req.method==='POST'){const b=await parse(req);const users=await get('users',[]),i=users.findIndex(x=>x.user_id===me.user_id);if(i<0||!(await verify(b.current||'',users[i].password_hash)))return json({error:'Current password incorrect'},400);users[i].password_hash=await hash(b.password);await set('users',users);await audit(me,'password_change','Changed own password');return json({ok:true})}
 if(path==='/settings'&&(req.method==='GET'||req.method==='PUT')){if(req.method==='GET')return json(await get('settings',{}));if(!full.has(me.role))return json({error:'Owner/Sports Teacher only'},403);const b=await parse(req);const s={...(await get('settings',{})),...b};await set('settings',s);await audit(me,'settings_update','Updated school settings');return json(s)}
 if(path==='/backup'&&req.method==='GET'){if(!full.has(me.role))return json({error:'Forbidden'},403);const names=['settings','users','students','events','results','participation','assessments','annual','certificates','gallery','teacher_profiles','prefect_profiles','audit'];const out={};for(const n of names)out[n]=await get(n,[]);return json(out)}
 const m=path.match(/^\/(students|events|results|participation|assessments|annual|certificates|gallery|teachers|prefects)(?:\/([^/]+)(?:\/(photo))?)?$/);if(!m)return json({error:'Not found'},404);let resource=m[1],id=m[2],sub=m[3];
 if(resource==='students'&&sub==='photo'&&req.method==='POST'){const students=await get('students',[]),i=students.findIndex(x=>x.id===id);if(i<0||!allowed(me,students[i]))return json({error:'Forbidden'},403);if(!staff.has(me.role))return json({error:'Forbidden'},403);const ct=req.headers.get('content-type')||'';if(!ct.startsWith('image/'))return json({error:'Image required'},400);const buf=Buffer.from(await req.arrayBuffer());if(buf.length>3*1024*1024)return json({error:'Image must be under 3 MB'},400);const key=`student/${id}/${Date.now()}`;await files.set(key,buf,{metadata:{contentType:ct}});students[i].photo_key=key;await set('students',students);await audit(me,'student_photo','Updated student photo');return json({ok:true,photo_key:key})}
 if(resource==='students'){let arr=await get('students',[]);if(req.method==='GET')return json(arr.filter(x=>me.role==='student'?x.admission_no===me.user_id:allowed(me,x)));if(!['owner','sports_teacher','house_teacher','prefect'].includes(me.role))return json({error:'Forbidden'},403);if(req.method==='POST'){const b=await parse(req);if(me.role==='house_teacher')b.house=me.house;if(!HOUSES.includes(b.house))return json({error:'Invalid house'},400);b.id=uid();b.created_at=new Date().toISOString();b.bmi=calcBMI(b.height,b.weight);arr.push(b);await set('students',arr);const users=await get('users',[]);users.push({id:uid(),user_id:b.admission_no,password_hash:await hash(b.admission_no),name:b.name,role:'student',active:true});await set('users',users);await audit(me,'student_add',b.admission_no);return json(b,201)}if(id){const i=arr.findIndex(x=>x.id===id);if(i<0||!allowed(me,arr[i]))return json({error:'Forbidden'},403);if(req.method==='DELETE'){if(!['owner','sports_teacher','house_teacher','prefect'].includes(me.role))return json({error:'Forbidden'},403);const old=arr.splice(i,1)[0];await set('students',arr);await audit(me,'student_delete',old.admission_no);return json({ok:true})}if(req.method==='PUT'){if(!['owner','sports_teacher','house_teacher'].includes(me.role))return json({error:'Only owner/sports teacher/house teacher can edit'},403);const b=await parse(req);if(me.role==='house_teacher'&&(b.house&&b.house!==me.house))return json({error:'House locked'},403);arr[i]={...arr[i],...b,bmi:calcBMI(b.height??arr[i].height,b.weight??arr[i].weight)};await set('students',arr);await audit(me,'student_update',arr[i].admission_no);return json(arr[i])}}}
 if(resource==='teachers'||resource==='prefects'){if(!full.has(me.role))return json({error:'Owner/Sports Teacher only'},403);const role=resource==='teachers'?'house_teacher':'prefect',key=resource==='teachers'?'teacher_profiles':'prefect_profiles';let arr=await get(key,[]);if(req.method==='GET')return json(arr);if(req.method==='POST'){const b=await parse(req);if(!b.user_id||!b.name)return json({error:'User ID and name required'},400);const users=await get('users',[]);if(users.some(x=>x.user_id===b.user_id))return json({error:'User ID already exists'},409);const password=b.password||b.user_id;users.push({id:uid(),user_id:b.user_id,password_hash:await hash(password),name:b.name,role,house:role==='house_teacher'?b.house:null,active:true});await set('users',users);b.id=uid();b.role=role;b.initial_password=password;await set(key,[...arr,b]);await audit(me,'account_create',`${role}:${b.user_id}`);return json({user_id:b.user_id,password,profile:b},201)}if(req.method==='DELETE'&&id){arr=arr.filter(x=>x.id!==id);await set(key,arr);const users=await get('users',[]);await set('users',users.filter(x=>x.id!==id));return json({ok:true})}}
 const maps={events:'events',results:'results',participation:'participation',assessments:'assessments',annual:'annual',certificates:'certificates',gallery:'gallery'};const key=maps[resource];if(key){let arr=await get(key,[]);if(req.method==='GET')return json(arr.filter(x=>allowed(me,x)||me.role==='student'&&x.student_id===me.user_id));if(!staff.has(me.role))return json({error:'Forbidden'},403);if(req.method==='POST'){if(resource==='gallery'){const form=await req.formData();const file=form.get('file');if(!file||typeof file.arrayBuffer!=='function')return json({error:'Image required'},400);if(file.size>5*1024*1024)return json({error:'Image must be under 5 MB'},400);const keyf=`gallery/${uid()}`;await files.set(keyf,Buffer.from(await file.arrayBuffer()),{metadata:{contentType:file.type||'image/jpeg'}});const b={id:uid(),file_key:keyf,caption:form.get('caption')||'',house:form.get('house')||'School Event',event:form.get('event')||'',uploader:me.user_id,date:new Date().toISOString()};arr.push(b);await set(key,arr);await audit(me,'gallery_add',b.id);return json(b,201)}const b=await parse(req);if(me.role==='house_teacher'&&b.house!==me.house)return json({error:'Assigned house only'},403);b.id=uid();b.created_at=new Date().toISOString();arr.push(b);await set(key,arr);await audit(me,`${resource}_add`,b.id);return json(b,201)}if(req.method==='DELETE'&&id&&full.has(me.role)){await set(key,arr.filter(x=>x.id!==id));return json({ok:true})}}
 }catch(e){console.error(e);return json({error:'Server error',detail:e.message},500)}};
function calcBMI(h,w){const H=Number(h),W=Number(w);return H>0&&W>0?Number((W/((H/100)**2)).toFixed(2)):''}
